### ISSUE TITLE
Request tweets

### ISSUE THREAD

**Issue by tai-abrahams** [funador/react-auth-client#13]
Hi, i have managed to complete the authorisation stage of this tutorial, i guess this isnt really an issue but would like help or maybe help directing me to a site displaying how to fetch/request tweets once the callback has been executed and has been authorised/logged-in. 

I have been on the twitter site and copied the code here : https://developer.twitter.com/en/docs/labs/tweets-and-users/quick-starts/get-tweets
and refactored to look like this on a separate twitter.js file to be imported into the App.js (App component). Heres my code:

///////////////////////////////////////start///////////////////////////////////////////////
tweet.js file

import React, { Component } from 'react';
const request = require('request');

const util = require('util')
const get= util.promisify(request.get);
const endpointURL = new URL('https://api.twitter.com/labs/1/tweets');

export default class Tweets extends Component {
state={
  tweets:''
}
componentDidMount(){
  async function getRequest(){
    const params = {
      ids: 'TLgXKh7bO0H_t9DeAAAq',
      format: 'detailed',
    };
    const req = await get({url:endpointURL, qs: params, json:true, mode: 'cors'});
    if( req.body ){
      return req.body;

    } else {
     console.log('not working working')
    }
  }

  (async ()=>{
    try{
      const response = await getRequest();
      console.log(response);
    } catch(e){
      console.error( e)
    }
  })();
  }

  render() {
    return(
      <div>
        <ul>
        {this.state.tweets
          ? this.state.tweets.map(el=>(<li>{el}</li>))
          : <div>Didnt fetch</div>}
      </ul>
    </div>
    )
  }
}

////////////////////////////////////////end//////////////////////////////////////////////

This is imported to the App.js file as such:

////////////////////////////////////////start//////////////////////////////////////////////
App.js fiile:

import React, { Component } from 'react'
import io from 'socket.io-client'
import OAuth from './OAuth'
import Loading from './Loading'
import Footer from './Footer'
import Tweets from './Tweets'
import { API_URL } from './config'
import './App.css'
const socket = io(API_URL) //,{transports: ['websocket']}
const providers = ['twitter', 'google', 'facebook', 'github']//import theese in because our auth controller needs to call our event for each provider which the event is named after the provider

export default class App extends Component {

  state = {
    loading: true
  }

  componentDidMount() {//check server and server route is working as created on server.js so to remove loading screen

    socket.on('connect', function(){
      console.log('connected')
    });

    fetch(`${API_URL}/wake-up`)
      .then(res => {
        if (res.ok) {
          this.setState({loading: false})
        }
      })
  }

  render() {
    const divStyles = {

    }
    const buttons = (providers, socket) =>
      providers.map(provider =>
        <OAuth
          provider={provider}
          key={provider}
          socket={socket}
        />
      )

    return (
      <div className='wrapper'>
        <div className='container'>
          {this.state.loading
            ? <Loading />
            : buttons(providers, socket)
          }
        </div>
{
buttons
? <Tweets provider='twitter' />
: <div> Hasnt fetched</div>
}
        <Footer />
      </div>
    )
  }
}

**Comment by funador** [comment]
This definitely isn't an issue... Going to close this. Perhaps better on stackoverflow.com
